In [2]:
import pandas as pd
import numpy as np

In [5]:
file_path = "../Data/raw/online_retail_II.xlsx"

retail_2009 = pd.read_excel(file_path, sheet_name="Year 2009-2010")
retail_2010 = pd.read_excel(file_path, sheet_name="Year 2010-2011")

In [8]:
retail_2009.shape

(525461, 8)

In [10]:
retail_2010.shape

(541910, 8)

In [11]:
retail_2009.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [12]:
retail_2010.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [13]:
retail_2009.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [14]:
retail_2010.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [15]:
retail_2009.columns.equals(retail_2010.columns)

True

In [17]:
retail_df = pd.concat([retail_2009, retail_2010], ignore_index=True)
retail_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [28]:
retail_df.shape

(1067371, 8)

In [25]:
retail_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [26]:
retail_df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [23]:
retail_df.describe()

           Quantity                 InvoiceDate         Price    Customer ID
count  1.067371e+06                     1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394029  4.649388e+00   15324.638504
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00         2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00         2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01         2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                         NaN  1.235531e+02    1697.464450

In [24]:
retail_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [34]:
missing = retail_df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

Customer ID    243007
Description      4382
dtype: int64

In [35]:
missing_percent = (retail_df.isnull().mean() * 100).round(2)

pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percent
}).sort_values("Percentage", ascending=False)

             Missing Values  Percentage
Customer ID          243007       22.77
Description            4382        0.41
Country                   0        0.00
Invoice                   0        0.00
InvoiceDate               0        0.00
Price                     0        0.00
Quantity                  0        0.00
StockCode                 0        0.00

In [38]:
duplicates = retail_df.duplicated().sum()
duplicates

np.int64(34335)

In [41]:
unique_values = retail_df.nunique().sort_values(ascending=False)
unique_values

Invoice        53628
InvoiceDate    47635
Customer ID     5942
Description     5698
StockCode       5305
Price           2807
Quantity        1057
Country           43
dtype: int64

In [43]:
print("Earliest Transaction :", retail_df["InvoiceDate"].min())
print("Latest Transaction   :", retail_df["InvoiceDate"].max())

Earliest Transaction : 2009-12-01 07:45:00
Latest Transaction   : 2011-12-09 12:50:00

In [44]:
cancelled = retail_df["Invoice"].astype(str).str.startswith("C").sum()

print(f"Cancelled Invoices : {cancelled:,}")

Cancelled Invoices : 19,494

In [45]:
print("Negative Quantity :", (retail_df["Quantity"] < 0).sum())
print("Zero Quantity     :", (retail_df["Quantity"] == 0).sum())

Negative Quantity : 22950
Zero Quantity     : 0

In [46]:
print("Negative Price :", (retail_df["Price"] < 0).sum())
print("Zero Price     :", (retail_df["Price"] == 0).sum())

Negative Price : 5
Zero Price     : 6202

In [47]:
print("Missing Customer IDs :", retail_df["Customer ID"].isnull().sum())
print("Unique Customers     :", retail_df["Customer ID"].nunique())

Missing Customer IDs : 243007
Unique Customers     : 5942

In [48]:
retail_df["Country"].value_counts()

Country
United Kingdom          981330
EIRE                     17866
Germany                  17624
France                   14330
Netherlands               5140
Spain                     3811
Switzerland               3189
Belgium                   3123
Portugal                  2620
Australia                 1913
Channel Islands           1664
Italy                     1534
Norway                    1455
Sweden                    1364
Cyprus                    1176
Finland                   1049
Austria                    938
Denmark                    817
Unspecified                756
Greece                     663
Japan                      582
USA                        535
Poland                     535
United Arab Emirates       500
Israel                     371
Hong Kong                  364
Singapore                  346
Malta                      299
Iceland                    253
Canada                     228
Lithuania                  189
RSA                        169
Bahrain                    126
Brazil                      94
Thailand                    76
Korea                       63
European Community          61
Lebanon                     58
West Indies                 54
Bermuda                     34
Nigeria                     32
Czech Republic              30
Saudi Arabia                10
Name: count, dtype: int64

In [49]:
print("Unique Products :", retail_df["StockCode"].nunique())
print("Unique Product Descriptions :", retail_df["Description"].nunique())

Unique Products : 5305
Unique Product Descriptions : 5698

In [50]:
retail_df["Revenue"] = retail_df["Quantity"] * retail_df["Price"]

retail_df[["Quantity", "Price", "Revenue"]].head()

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

In [51]:
retail_df.sample(10, random_state=42)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
455941,532657,21314,SMALL GLASS HEART TRINKET POT,12,2010-11-14 11:10:00,2.10,14562.0,United Kingdom,25.20
826291,563214,22383,LUNCH BAG SUKI DESIGN,2,2011-08-14 12:56:00,1.65,16370.0,United Kingdom,3.30
191636,507597,22561,WOODEN SCHOOL COLOURING SET,12,2010-05-10 13:21:00,1.65,17700.0,United Kingdom,19.80
25864,491634,21588,RETRO SPOT GIANT TUBE MATCHES,1,2009-12-11 15:40:00,2.55,17841.0,United Kingdom,2.55
73233,496007,85232B,SET/3 RUSSIAN DOLL STACKING TINS,3,2010-01-28 12:32:00,4.95,15203.0,United Kingdom,14.85
557542,539041,21832,CHOCOLATE CALCULATOR,4,2010-12-15 15:34:00,1.65,15456.0,United Kingdom,6.60
985772,575905,22089,PAPER BUNTING VINTAGE PAISLEY,6,2011-11-11 15:49:00,2.95,13732.0,United Kingdom,17.70
568585,540026,21519,GIN & TONIC DIET GREETING CARD,2,2011-01-04 13:25:00,0.85,NaN,United Kingdom,1.70
530265,536804,22988,SOLDIERS EGG CUP,72,2010-12-02 16:34:00,1.25,14031.0,United Kingdom,90.00
649024,546899,20719,WOODLAND CHARLOTTE BAG,50,2011-03-17 18:27:00,0.72,14298.0,United Kingdom,36.00

In [53]:
# ==========================================================
# COMPLETE DATASET INSPECTION
# ==========================================================

import pandas as pd

print("="*80)
print("DATASET OVERVIEW")
print("="*80)

print(f"Rows               : {retail_df.shape[0]:,}")
print(f"Columns            : {retail_df.shape[1]}")
print(f"Date Range         : {retail_df['InvoiceDate'].min()}  -->  {retail_df['InvoiceDate'].max()}")

print("\nColumn Names:")
print(retail_df.columns.tolist())

# ==========================================================
print("\n" + "="*80)
print("DATA TYPES & MEMORY")
print("="*80)

retail_df.info()

# ==========================================================
print("\n" + "="*80)
print("NUMERICAL SUMMARY")
print("="*80)

display(retail_df.describe().T)

print("\n" + "="*80)
print("CATEGORICAL SUMMARY")
print("="*80)

display(retail_df.describe(include="object").T)

# ==========================================================
print("\n" + "="*80)
print("MISSING VALUES")
print("="*80)

missing = pd.DataFrame({
    "Missing Values": retail_df.isnull().sum(),
    "Percentage (%)": (retail_df.isnull().mean()*100).round(2)
})

display(missing.sort_values("Missing Values", ascending=False))

# ==========================================================
print("\n" + "="*80)
print("DUPLICATE ROWS")
print("="*80)

duplicates = retail_df.duplicated().sum()
print(f"Duplicate Rows : {duplicates:,}")

# ==========================================================
print("\n" + "="*80)
print("UNIQUE VALUES")
print("="*80)

display(pd.DataFrame({
    "Unique Values": retail_df.nunique()
}).sort_values("Unique Values"))

# ==========================================================
print("\n" + "="*80)
print("BUSINESS QUALITY CHECKS")
print("="*80)

cancelled = retail_df["Invoice"].astype(str).str.startswith("C").sum()

negative_qty = (retail_df["Quantity"] < 0).sum()
zero_qty = (retail_df["Quantity"] == 0).sum()

negative_price = (retail_df["Price"] < 0).sum()
zero_price = (retail_df["Price"] == 0).sum()

missing_customers = retail_df["Customer ID"].isnull().sum()

print(f"Cancelled Invoices     : {cancelled:,}")
print(f"Negative Quantity      : {negative_qty:,}")
print(f"Zero Quantity          : {zero_qty:,}")
print(f"Negative Price         : {negative_price:,}")
print(f"Zero Price             : {zero_price:,}")
print(f"Missing Customer IDs   : {missing_customers:,}")

# ==========================================================
print("\n" + "="*80)
print("CUSTOMER INSIGHTS")
print("="*80)

print(f"Unique Customers : {retail_df['Customer ID'].nunique():,}")

# ==========================================================
print("\n" + "="*80)
print("PRODUCT INSIGHTS")
print("="*80)

print(f"Unique Stock Codes         : {retail_df['StockCode'].nunique():,}")
print(f"Unique Product Descriptions: {retail_df['Description'].nunique():,}")

# ==========================================================
print("\n" + "="*80)
print("COUNTRY INSIGHTS")
print("="*80)

print(f"Number of Countries : {retail_df['Country'].nunique()}")

display(retail_df["Country"].value_counts().head(20))

# ==========================================================
print("\n" + "="*80)
print("TOP PRODUCTS")
print("="*80)

display(retail_df["Description"].value_counts().head(20))

# ==========================================================
print("\n" + "="*80)
print("REVENUE")
print("="*80)

retail_df["Revenue"] = retail_df["Quantity"] * retail_df["Price"]

print(f"Total Revenue (Raw Dataset): {retail_df['Revenue'].sum():,.2f}")

display(retail_df[["Quantity","Price","Revenue"]].head())

# ==========================================================
print("\n" + "="*80)
print("RANDOM SAMPLE")
print("="*80)

display(retail_df.sample(10, random_state=42))

================================================================================
DATASET OVERVIEW
================================================================================
Rows               : 1,067,371
Columns            : 9
Date Range         : 2009-12-01 07:45:00  -->  2011-12-09 12:50:00

Column Names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'Revenue']

================================================================================
DATA TYPES & MEMORY
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
 8   Revenue      1067371 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(3), str(1)
memory usage: 73.3+ MB

================================================================================
NUMERICAL SUMMARY
================================================================================

,count,mean,min,25%,50%,75%,max,std
Quantity,1067371.0,9.938898,-80995.0,1.0,3.0,10.0,80995.0,172.705794
InvoiceDate,1067371,2011-01-02 21:13:55.394029,2009-12-01 07:45:00,2010-07-09 09:46:00,2010-12-07 15:28:00,2011-07-22 10:23:00,2011-12-09 12:50:00,NaN
Price,1067371.0,4.649388,-53594.36,1.25,2.1,4.15,38970.0,123.553059
Customer ID,824364.0,15324.638504,12346.0,13975.0,15255.0,16797.0,18287.0,1697.46445
Revenue,1067371.0,18.069866,-168469.6,3.75,9.9,17.7,168469.6,292.420223

================================================================================
CATEGORICAL SUMMARY
================================================================================

C:\Users\manoh\AppData\Local\Temp\ipykernel_16684\3637243762.py:36: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(retail_df.describe(include="object").T)

               count unique                                 top    freq
Invoice      1067371  53628                              537434    1350
StockCode    1067371   5305                              85123A    5829
Description  1062989   5698  WHITE HANGING HEART T-LIGHT HOLDER    5918
Country      1067371     43                      United Kingdom  981330

================================================================================
MISSING VALUES
================================================================================

             Missing Values  Percentage (%)
Customer ID          243007           22.77
Description            4382            0.41
Invoice                   0            0.00
Quantity                  0            0.00
StockCode                 0            0.00
InvoiceDate               0            0.00
Price                     0            0.00
Country                   0            0.00
Revenue                   0            0.00

================================================================================
DUPLICATE ROWS
================================================================================
Duplicate Rows : 34,335

================================================================================
UNIQUE VALUES
================================================================================

             Unique Values
Country                 43
Quantity              1057
Price                 2807
StockCode             5305
Description           5698
Customer ID           5942
Revenue               9113
InvoiceDate          47635
Invoice              53628

================================================================================
BUSINESS QUALITY CHECKS
================================================================================
Cancelled Invoices     : 19,494
Negative Quantity      : 22,950
Zero Quantity          : 0
Negative Price         : 5
Zero Price             : 6,202
Missing Customer IDs   : 243,007

================================================================================
CUSTOMER INSIGHTS
================================================================================
Unique Customers : 5,942

================================================================================
PRODUCT INSIGHTS
================================================================================
Unique Stock Codes         : 5,305
Unique Product Descriptions: 5,698

================================================================================
COUNTRY INSIGHTS
================================================================================
Number of Countries : 43

Country
United Kingdom     981330
EIRE                17866
Germany             17624
France              14330
Netherlands          5140
Spain                3811
Switzerland          3189
Belgium              3123
Portugal             2620
Australia            1913
Channel Islands      1664
Italy                1534
Norway               1455
Sweden               1364
Cyprus               1176
Finland              1049
Austria               938
Denmark               817
Unspecified           756
Greece                663
Name: count, dtype: int64

================================================================================
TOP PRODUCTS
================================================================================

Description
WHITE HANGING HEART T-LIGHT HOLDER    5918
REGENCY CAKESTAND 3 TIER              4412
JUMBO BAG RED RETROSPOT               3469
ASSORTED COLOUR BIRD ORNAMENT         2958
PARTY BUNTING                         2765
STRAWBERRY CERAMIC TRINKET BOX        2613
LUNCH BAG  BLACK SKULL.               2529
JUMBO STORAGE BAG SUKI                2434
HEART OF WICKER SMALL                 2319
JUMBO SHOPPER VINTAGE RED PAISLEY     2297
60 TEATIME FAIRY CAKE CASES           2271
PAPER CHAIN KIT 50'S CHRISTMAS        2215
LUNCH BAG SPACEBOY DESIGN             2206
REX CASH+CARRY JUMBO SHOPPER          2199
HOME BUILDING BLOCK WORD              2192
WOODEN FRAME ANTIQUE WHITE            2189
LUNCH BAG CARS BLUE                   2184
NATURAL SLATE HEART CHALKBOARD        2151
BAKING SET 9 PIECE RETROSPOT          2150
POSTAGE                               2115
Name: count, dtype: int64

================================================================================
REVENUE
================================================================================
Total Revenue (Raw Dataset): 19,287,250.57

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

================================================================================
RANDOM SAMPLE
================================================================================

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
455941,532657,21314,SMALL GLASS HEART TRINKET POT,12,2010-11-14 11:10:00,2.10,14562.0,United Kingdom,25.20
826291,563214,22383,LUNCH BAG SUKI DESIGN,2,2011-08-14 12:56:00,1.65,16370.0,United Kingdom,3.30
191636,507597,22561,WOODEN SCHOOL COLOURING SET,12,2010-05-10 13:21:00,1.65,17700.0,United Kingdom,19.80
25864,491634,21588,RETRO SPOT GIANT TUBE MATCHES,1,2009-12-11 15:40:00,2.55,17841.0,United Kingdom,2.55
73233,496007,85232B,SET/3 RUSSIAN DOLL STACKING TINS,3,2010-01-28 12:32:00,4.95,15203.0,United Kingdom,14.85
557542,539041,21832,CHOCOLATE CALCULATOR,4,2010-12-15 15:34:00,1.65,15456.0,United Kingdom,6.60
985772,575905,22089,PAPER BUNTING VINTAGE PAISLEY,6,2011-11-11 15:49:00,2.95,13732.0,United Kingdom,17.70
568585,540026,21519,GIN & TONIC DIET GREETING CARD,2,2011-01-04 13:25:00,0.85,NaN,United Kingdom,1.70
530265,536804,22988,SOLDIERS EGG CUP,72,2010-12-02 16:34:00,1.25,14031.0,United Kingdom,90.00
649024,546899,20719,WOODLAND CHARLOTTE BAG,50,2011-03-17 18:27:00,0.72,14298.0,United Kingdom,36.00

In [59]:
output_path = "../data/interim/retail_merged.parquet"

try:
    retail_df.to_parquet(output_path, index=False)
    print("Merged dataset saved successfully!")
except ImportError:
    fallback_path = output_path.replace(".parquet", ".csv")
    retail_df.to_csv(fallback_path, index=False)
    print(f"Parquet engine not available. Saved as CSV instead: {fallback_path}")

print("Merged dataset saved successfully!")

Parquet engine not available. Saved as CSV instead: ../data/interim/retail_merged.csv
Merged dataset saved successfully!