In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("../Data/interim/retail_merged.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [36]:
df.shape

(1067371, 9)

In [37]:
df = df.drop_duplicates()
df.shape

(1033036, 9)

In [38]:
cancelled = df["Invoice"].astype(str).str.startswith("C")
cancelled.shape

(1033036,)

In [39]:
df = df[~cancelled]
df.shape

(1013932, 9)

In [40]:
print(f"Removing {(df['Quantity'] <= 0).sum():,} invalid quantities...")

Removing 3,393 invalid quantities...

In [41]:
df = df[df["Quantity"] > 0]
df.shape

(1010539, 9)

In [42]:
print(f"Removing {(df['Price'] <= 0).sum():,} invalid prices...")

Removing 2,626 invalid prices...

In [43]:
df = df[df["Price"] > 0]
df.shape

(1007913, 9)

In [48]:
print(f"Removing {df['Description'].isna().sum():,} missing descriptions...")

Removing 0 missing descriptions...

In [57]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [58]:
df["Year"] = df["InvoiceDate"].dt.year
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009

In [59]:
df["Month"] = df["InvoiceDate"].dt.month
df["MonthName"] = df["InvoiceDate"].dt.month_name()
df["Quarter"] = df["InvoiceDate"].dt.quarter
df["Day"] = df["InvoiceDate"].dt.day
df["DayName"] = df["InvoiceDate"].dt.day_name()
df["Hour"] = df["InvoiceDate"].dt.hour
df["Weekday"] = df["InvoiceDate"].dt.weekday

In [60]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,MonthName,Quarter,Day,DayName,Hour,Weekday
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,December,4,1,Tuesday,7,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,4,1,Tuesday,7,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,4,1,Tuesday,7,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,December,4,1,Tuesday,7,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,December,4,1,Tuesday,7,1

In [61]:
df.shape

(1007913, 17)

In [64]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [65]:
print("\n" + "="*80)
print("FINAL DATASET")
print("="*80)

print(f"Final Shape : {df.shape}")

print("\nMissing Values")
display(df.isnull().sum())

print("\nData Types")
display(df.dtypes)

print("\nRevenue")
print(f"Total Revenue : {df['Revenue'].sum():,.2f}")

display(df.head())

================================================================================
FINAL DATASET
================================================================================
Final Shape : (1007913, 17)

Missing Values

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    228488
Country             0
Revenue             0
Year                0
Month               0
MonthName           0
Quarter             0
Day                 0
DayName             0
Hour                0
Weekday             0
dtype: int64

Data Types

Invoice                   str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
Revenue               float64
Year                    int32
Month                   int32
MonthName                 str
Quarter                 int32
Day                     int32
DayName                   str
Hour                    int32
Weekday                 int32
dtype: object

Revenue
Total Revenue : 20,476,260.45

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,MonthName,Quarter,Day,DayName,Hour,Weekday
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,December,4,1,Tuesday,7,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,4,1,Tuesday,7,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,4,1,Tuesday,7,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,December,4,1,Tuesday,7,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,December,4,1,Tuesday,7,1

### Saving the processed Data

In [70]:
df.to_csv("../Data/processed/final_retail.csv", index=False)